# Generated by Django 4.2.1 on 2023-05-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='avgrage_rating',
            field=models.FloatField(default=0),
        ),
    ]
