# Generated by Django 4.2.1 on 2023-05-25 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment_created_at_comment_is_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='avgrage_rating',
            new_name='average_rating',
        ),
        migrations.AlterField(
            model_name='rate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.project'),
        ),
    ]
