# Generated by Django 4.2.1 on 2023-05-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_avgrage_rating_project_average_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='target',
            new_name='target_donations',
        ),
        migrations.AddField(
            model_name='project',
            name='current_donations',
            field=models.IntegerField(default=0),
        ),
    ]
