# Generated by Django 4.2.1 on 2023-05-27 18:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_project_is_featured_delete_featuredprojects'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user', 'project')},
        ),
    ]
